# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 537029bb4504e1ba51f4c0a62f8571800bf35eebc3f7d692e2a8487ff9b9a5b80e61927bfca9f1dcfaf54027ddc08022c6765c2170215b4379ae4fb7ac1fe6f0

test:
  secret_key_base: 3747c9051639b54542c2bb991d04151e79fa5e991be4f0c25e3be8582f263728f640675b882158584b17568be371d84a8c95431de867206f66c0c8f91002b2ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
